##
# Binds
##

######
# Rebind prefix
# Alt + n || Ctrl + n
# NOT WORKING alt + n
set-option -g prefix C-n
bind-key C-n send-prefix
bind-key -T root M-n send-keys C-n

###
# Windows
######

# Resize
bind < resize-pane -L 10
bind > resize-pane -R 10
bind _ resize-pane -D 10
bind + resize-pane -U 10

##
# Create panel
##

unbind c
unbind C
bind c command-prompt -p "\
#{@command-prefix}\
Window name: " \
"new-window -c '#{pane_current_path}' -n %%"

bind C new-window -c "#{pane_current_path}"

unbind '"'
bind '"' split-window -c "#{pane_current_path}"

unbind %
bind % split-window -h -c "#{pane_current_path}"

# Rebind ro reload config
unbind r
bind r source-file '~/.config/tmux/tmux.conf' \; display ".tmux.conf Reloaded!"

##
# Sessions
##

# Create new (auto number)
# Prefix + N (New)
unbind N
bind N new-session

# Choose session (interactive)
# Prefix + e (Session)
bind e choose-tree -Z

# Prefix + S (Switch) - Быстрый выбор сессии по имени
unbind S
# bind S switch-client -t

# Prefix + H (History/Prev)
# bind H previous-session

# Prefix + L (Last/Next)
# bind L next-session

# Kill session
# Prefix + W (Kill Session)
bind W confirm-before -p "Kill session #S? (y/n)" kill-session
