##
# Base
##

set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*256col*:Tc"
set -g display-time 3000
set -g escape-time 0
set -g history-limit 65535
set -g detach-on-destroy off
set -g set-clipboard on
set -g renumber-windows on

# Start all numbering with 1
set -g base-index 1
set -g pane-base-index 1

# Enable mouse support
set-option -g mouse on

# Vim motions
setw -g mode-keys vi

set-option -s focus-events on
set-option -s extended-keys on

