##
# Base
##

set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'
set -g display-time 3000
set -g escape-time 0
set -g history-limit 65535
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g set-clipboard on          # use system clipboard
set -g renumber-windows on

# Start all numbering with 1
set -g base-index 1
set -g pane-base-index 1

# Enable mouse support
set-option -g mouse on

# Vim motions
setw -g mode-keys vi

# Enable extended support for some more sophisticated terminal emulator
# features. Disable them if they are causing problems!
set-option -s focus-events on
set-option -s extended-keys on

