##
# Theme
##

# Overall look
set-option -g status-style "fg=#{@thm_color100},bg=#{@thm_color700}"

# Show the window list centered between the left and the right section
set-option -g status-justify absolute-centre

# Right side
set-option -g status-right "\
#[fg=#{@thm_crimson},bg=default]\
#[fg=#{@thm_color100},bg=#{@thm_crimson}]  \
#[fg=#{@thm_crimson},bg=#{@thm_color700}] \
#[fg=#{@thm_color100},bg=#{@thm_color700}]#h \
#[fg=#{@thm_crimson},bg=#{@thm_color700}] \
#[fg=#{@thm_crimson},bg=#{@thm_color700}]\
"

# Left side
set-option -g status-left "\
#[fg=#{?client_prefix,#{@thm_gold},#{@thm_bloom}},bg=default]\
#[fg=#{@thm_color700},bg=#{?client_prefix,#{@thm_gold},#{@thm_bloom}}]\
 #{?client_prefix, , } \
#[fg=#{?client_prefix,#{@thm_gold},#{@thm_bloom}},bg=#{@thm_color700}] \
#[fg=default] #S\
"

# Windows
set-option -g window-status-format "\
#[fg=#{@thm_crimson},bg=default]  \
#[fg=#{@thm_color700},bg=#{@thm_crimson}] \
#[fg=#{@thm_color700},bg=#{@thm_crimson}]#I \
#[fg=#{@thm_crimson},bg=#{@thm_color700}] \
#[fg=default]#W\
"

# Window current
set-option -g window-status-current-format "\
#[fg=#{@thm_primary},bg=default]  \
#[fg=#{@thm_color700},bg=#{@thm_primary}] \
#[fg=#{@thm_color700},bg=#{@thm_primary}]#I \
#[fg=#{@thm_primary},bg=#{@thm_color700}] \
#[fg=default]#W\
"

# Remove the separator between window list items, as we already have spacing
# "around" inactive items
set-option -g window-status-separator ""
set-option -g status-position top

# Length limits
set-option -g status-left-length 100
set-option -g status-right-length 100

# Fix Terminal Title display, to not contain tmux specic information
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

set-option -g message-style "fg=#{@thm_gold},bg=#{@thm_color700},bold"

# Позиция промпта (0 = статус-бар, 1-4 = строки выше)
set-option -g message-line 0
