# Rebind prefix
# unbind C-b
set-option -g prefix C-a

# Start all numbering with 1
set -g base-index 1
set -g pane-base-index 1

# Enable mouse support
set-option -g mouse on

# Vim motions
setw -g mode-keys vi

##
# Theme
##

# Enable theme
source-file $HOME/.config/tmux/theme/yugen-ash.conf

set-option -g status-style "fg=#{@thm_color100},bg=#{@thm_color700}"

# Show the window list centered between the left and the right section
set-option -g status-justify absolute-centre

# Right side
set-option -g status-right "\
#[fg=#{@thm_crimson},bg=default]\
#[fg=#{@thm_color100},bg=#{@thm_crimson}]  \
#[fg=#{@thm_crimson},bg=#{@thm_color700}] \
#[fg=#{@thm_color100},bg=#{@thm_color700}]#h \
#[fg=#{@thm_crimson},bg=#{@thm_color700}] \
#[fg=#{@thm_crimson},bg=#{@thm_color700}]\
"

# Windows
set-option -g window-status-format "\
#[fg=#{@thm_primary},bg=default]\
#[fg=#{@thm_color700},bg=#{@thm_primary}] \
#[fg=#{@thm_color700},bg=#{@thm_primary}]#I \
#[fg=#{@thm_primary},bg=#{@thm_color700}] \
#[fg=default]#W\
"

# Window current
set-option -g window-status-current-format "\
#[fg=#{@thm_primary},bg=default]\
#[fg=#{@thm_color700},bg=#{@thm_primary}] \
#[fg=#{@thm_color700},bg=#{@thm_primary}]#I \
#[fg=#{@thm_primary},bg=#{@thm_color700}] \
#[fg=default]#W\
"

# Left side
set-option -g status-left "#S "

# Length limits
set-option -g status-left-length 100
set-option -g status-right-length 100

# Base
set -g default-terminal "screen-256color"
set -g display-time 3000
set -g escape-time 0
set -g history-limit 65535

# Fix Terminal Title display, to not contain tmux specic information
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

# Open new windows and panes in the current working directory of the active
# pane.
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Enable extended support for some more sophisticated terminal emulator
# features. Disable them if they are causing problems!
set-option -s focus-events on
set-option -s extended-keys on

# Rebind ro reload config
unbind r
bind r source-file ~/.config/tmux/.tmux.conf \; display ".tmux.conf Reloaded!"

# Map panel switch.
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R

# Resize
bind < resize-pane -L 10
bind > resize-pane -R 10
bind _ resize-pane -D 10
bind + resize-pane -U 10

# Remove the separator between window list items, as we already have spacing
# "around" inactive items
set-option -g window-status-separator ""
set-option -g status-position top
