# Structer

# Theme and const go first
source-file $HOME/.config/tmux/themes/yugen-ash.conf
source-file $HOME/.config/tmux/themes/elements.conf

source-file $HOME/.config/tmux/options.conf
source-file $HOME/.config/tmux/binds.conf
source-file $HOME/.config/tmux/panel.conf

# Must be always last
source-file $HOME/.config/tmux/plugins.conf
